"""One hundred authored concepts. Re-running preserves existing production statuses."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
# slug | title | role | function and story | required breakthrough | B | C
DOMAINS={
'orbit':'''light-sail|LIGHT SAIL|PHOTON CARGO CLIPPER|Moves delicate freight between heliocentric depots on sunlight. The manifest arrives before the ship; neither is in a hurry.|A sail that repairs micrometeoroid tears without losing its optical coating.|REEFING HUB|SAIL ROOT
ring-tender|RING TENDER|ORBITAL DOCKING TUG|Collects unpowered cargo pods with a split capture ring and carries them to a station without firing a plume at the windows.|Autonomous contact planning for tumbling cargo with unknown mass distribution.|CAPTURE JAWS|THRUSTER CRADLE
sweep-net|SWEEP NET|DEBRIS RETRIEVAL CRAFT|Encloses a tracked fragment in a tensioned net before towing it into a disposal orbit. The net is always cheaper than the satellite it missed.|Reliable capture of rotating fragments without creating smaller debris.|NET CASSETTE|TETHER WINCH
petal-eye|PETAL EYE|DEPLOYABLE INFRARED OBSERVATORY|Unfolds a segmented primary mirror behind a layered sunshade to study cold worlds beyond the familiar planets.|Metrology that keeps a repaired mirror phased after years of thermal cycling.|MIRROR HINGE|SECONDARY SPIDER
wheelhouse|WHEELHOUSE|ROTATING CREW HABITAT|Provides a quiet rotating sleeping ring around a nonrotating docking spine. The corridor has a horizon again.|Low-maintenance rotating pressure joints and comfortable artificial-gravity operations.|HUB BEARING|PRESSURE SPOKE
ice-mule|ICE MULE|ASTEROID WATER HAULER|Clamps a cold water package to an open truss and nudges it between orbital stores with electric propulsion.|Lossless long-duration cryogenic storage without a heavy consumable shield.|COLD TANK NECK|ION THRUSTER
shade-courier|SHADE COURIER|SOLAR SHIELD SERVICER|Carries folded replacement panels along the dark side of a large orbital sunshade and stitches them into place.|Robotic repair of extremely thin membranes under weak, changing tension.|PANEL MAGAZINE|SEAM HEAD
regolith-kite|REGOLITH KITE|LUNAR BAG LOADER|Hovers on a fixed cable above a lunar excavation and transfers sealed bags into a waiting hopper, keeping the abrasive dust outside its joints.|Long-lived dust seals for repeated handling of sharp lunar grains.|BAG GRIPPER|SEALED HOIST
comet-anchor|COMET ANCHOR|LOW-GRAVITY SAMPLE LANDER|Secures a sampling station to a weak icy surface with several shallow anchors rather than trusting its own weight.|Anchoring that adapts to unknown porous ice without fracturing the sample site.|ANCHOR FOOT|SAMPLE CAROUSEL
star-post|STAR POST|DEEP-SPACE OPTICAL RELAY|Maintains narrow optical links between remote probes while a gimballed aperture follows each slow conversation.|Autonomous optical acquisition after long communication blackouts.|STEERING MIRROR|CRYO RECEIVER''',
'energy':'''tidal-loom|TIDAL LOOM|BIDIRECTIONAL CURRENT HARVESTER|Extracts power from a reversing tidal stream with paired shrouded rotors. Fish receive a much wider corridor than the technicians do.|Low-loss marine bearings and reliable animal-aware control over decades underwater.|ROTOR CARTRIDGE|GUIDE VANE
inertia-bank|INERTIA BANK|MODULAR FLYWHEEL STORE|Banks short power surges in counter-rotating flywheels so that a neighbourhood can start its machinery without dimming every kitchen.|Containment and magnetic bearings that remain economical at community scale.|ROTOR STACK|BEARING CAGE
ember-vault|EMBER VAULT|SOLID HEAT RESERVOIR|Stores surplus electricity in replaceable hot ceramic blocks and returns useful heat after sunset.|Durable high-temperature contacts and insulation that survives daily thermal cycling.|CERAMIC CORE|HEAT EXCHANGER
mantle-needle|MANTLE NEEDLE|CLOSED-LOOP GEOTHERMAL DRILL|Cuts a deep closed-loop well with an electrically assisted drilling head. Heat comes back in a sealed circuit; groundwater stays underground.|A drill string and electronics that tolerate hot fractured rock for long service intervals.|DRILL CROWN|RETURN MANIFOLD
wind-kite|WIND KITE|TETHERED AIRBORNE GENERATOR|Flies repeating crosswind arcs while a ground winch converts tether tension into electricity. It lands before the storm rather than arguing with it.|Predictable unattended launch, landing and tether inspection in variable weather.|TETHER DRUM|WING SPAR
salt-delta|SALT DELTA|SALINITY-GRADIENT POWER STACK|Harvests part of the mixing energy where freshwater meets saltwater, routing both streams through serviceable membrane cassettes.|Cheap selective membranes that resist fouling without damaging the estuary.|MEMBRANE CASSETTE|FLOW DISTRIBUTOR
sun-fold|SUN FOLD|ARTICULATED SOLAR CANOPY|Unfolds reflective wings over a public charging court and folds them flat before high winds arrive.|Fatigue-resistant hinges and low-cost optical alignment across thousands of weather cycles.|FACET ACTUATOR|RECEIVER HEAD
pulse-reef|PULSE REEF|WAVE-DRIVEN LINEAR GENERATOR|Lets a floating collar rise and fall around a moored spar, taking power from the relative motion rather than fighting the sea.|Long-lived submerged linear generators and gentle mooring loads in extreme waves.|MAGNET TRANSLATOR|MOORING SWIVEL
night-cell|NIGHT CELL|RADIATIVE COOLING ENGINE|Exposes a selective radiator to the night sky and uses the temperature difference to support low-power field sensors.|Efficient conversion at small temperature differences and durable spectrally selective surfaces.|RADIATOR LAMINATE|THERMAL BRIDGE
district-heart|DISTRICT HEART|REVERSIBLE HEAT-PUMP STATION|Moves waste heat from workshops into a district loop and reverses its role when summer makes the same buildings need cooling.|Serviceable high-temperature compressors using low-impact working fluids.|COMPRESSOR SCROLL|VALVE BRIDGE''',
'water':'''dew-crown|DEW CROWN|ATMOSPHERIC WATER COLLECTOR|Opens a crown of condensing leaves above an isolated camp and collects water during suitable cool nights.|Coatings that shed clean droplets despite dust and repeated dry seasons.|CONDENSING LEAF|COLLECTION THROAT
river-sieve|RIVER SIEVE|LOW-PRESSURE MEMBRANE RAFT|Filters a controlled side stream of river water from a floating service raft while leaving the main channel open.|Long-life membranes cleaned by gentle mechanical motion rather than frequent chemical dosing.|MEMBRANE DRUM|BACKWASH VALVE
brine-garden|BRINE GARDEN|SELECTIVE MINERAL RECOVERY SKID|Separates useful salts from a managed brine stream instead of sending every dissolved mineral to the same waste pond.|Electrodes that distinguish competing ions with low energy and little chemical consumption.|ION CASSETTE|PRECIPITATION TRAY
ice-stitcher|ICE STITCHER|SEASONAL ICE REPAIR SLED|Pumps water into thin winter cracks and meters freezing in small layers around vulnerable field equipment.|Reliable prediction of local ice growth without overloading the surrounding sheet.|FREEZE SHOE|METERING PUMP
flood-lung|FLOOD LUNG|DEPLOYABLE FLOODWATER PUMP|Unrolls large flexible suction lines and raises a portable pump above rising water. The handles are still where a gloved hand expects them.|Abrasion-tolerant impellers that keep working through mixed flood debris.|IMPELLER BELL|HOSE COUPLING
mist-spire|MIST SPIRE|FOG INTERCEPTION TOWER|Raises porous collecting panels into a coastal fog corridor and guides droplets into a covered cistern.|Self-cleaning fibres that retain collection performance under salt, wind and ultraviolet exposure.|FIBRE PANEL|GUTTER JOINT
well-warden|WELL WARDEN|AQUIFER MONITORING STATION|Lowers a serviceable sensor string through one observation well and reports changes before a whole region notices its taps.|Stable in-situ chemical sensors that can recalibrate without bringing the probe back to the surface.|SENSOR STRING|CABLE SEAL
blue-loop|BLUE LOOP|HOUSEHOLD GREYWATER RECOVERY|Separates a home's lightly used water into cleaning, membrane treatment and a clearly separate reuse supply.|Compact treatment that stays safe and maintainable despite unpredictable household inputs.|BIOFILM CARTRIDGE|DIVERTER BLOCK
silt-heron|SILT HERON|SEDIMENT-SAMPLING WALKER|Steps through shallow mud on broad feet and takes short undisturbed cores between reed roots.|Gentle autonomous footing and contamination-free handling of fragile sediment layers.|CORE BARREL|BROAD FOOT
cloud-cistern|CLOUD CISTERN|AIRSHIP WATER RESERVE|Carries a modular reserve of water over difficult ground and lowers tanks onto prepared pads without an airstrip.|Low-maintenance buoyant envelopes and precise cargo exchange in gusty conditions.|TANK CRADLE|LOAD TRANSFER WINCH''',
'biology':'''seed-courier|SEED COURIER|PRECISION RESTORATION DRONE|Places diverse seed capsules into mapped patches of disturbed land, leaving existing plants and occupied nests alone.|Reliable ecological sensing that distinguishes an empty patch from a habitat worth leaving untouched.|SEED INDEXER|SOIL DART
pollen-steward|POLLEN STEWARD|GREENHOUSE POLLINATION ROVER|Carries a compliant flower tool between greenhouse rows when natural pollinators cannot enter the enclosure.|Vision and soft contact control that adapt to many flower shapes without bruising them.|SOFT POLLINATOR|POLLEN RESERVOIR
root-post|ROOT POST|SUBSURFACE ROOT-TREATMENT LANCE|Places tiny measured doses beside a tree's active roots instead of treating the whole lawn around it.|Root mapping accurate enough to guide a lance without cutting the roots it intends to help.|MICRODOSE TIP|ROOT SCANNER
mycelium-loom|MYCELIUM LOOM|GROWN-FIBRE PANEL PRESS|Grows structural fibre panels in a breathable mold, then dries them into a predictable shape for local construction.|Biological growth with repeatable strength, low contamination and controlled final dimensions.|BREATHABLE MOLD|DRYING PLENUM
coral-cradle|CORAL CRADLE|REEF NURSERY TENDER|Holds nursery fragments in a gentle current and transfers them to mapped restoration sites with a compliant tool.|Long-lived underwater handling that avoids damaging living tissue during repeated relocation.|FRAGMENT GRIPPER|NURSERY TILE
spore-library|SPORE LIBRARY|LIVING CULTURE ARCHIVE|Stores small verified cultures in individually serviced environmental drawers. A library card includes a genome check.|Automated viability checks that do not consume the last healthy sample.|CULTURE DRAWER|STERILE TRANSFER PORT
canopy-weaver|CANOPY WEAVER|ARBORIST CABLE ROBOT|Moves between approved tree anchors to inspect stressed branches and place protective supports without climbing spikes.|Reliable cable planning in living, moving structures with strict limits on bark pressure.|BARK SADDLE|TENSION HEAD
algae-ribbon|ALGAE RIBBON|THIN-FILM BIOREACTOR|Carries a sunlit film of culture through a stacked transparent loop so light and gas exchange reach the growing cells.|Productive strains and cleanable surfaces that remain stable outside laboratory conditions.|FILM CHANNEL|GAS EXCHANGE COMB
soil-choir|SOIL CHOIR|DISTRIBUTED ROOT-ZONE PROBE|Combines many quiet soil probes into a picture of moisture, chemistry and root activity. No single sensor gets to declare the whole field thirsty.|Low-drift sensors and models that distinguish crop demand from local soil variation.|PROBE TINE|FIELD HUB
orchard-tender|ORCHARD TENDER|SOFT-FINGER FRUIT HARVESTER|Selects ripe fruit inside a dense canopy and places it into shallow trays without dropping it through the machine.|Tactile harvesting that works across changing varieties, light and branch motion.|SOFT GRIPPER|CUSHIONED TRAY''',
'fabrication':'''glass-river|GLASS RIVER|CONTINUOUS GLASS EXTRUDER|Draws recycled glass into repair panels through a controlled hot channel, keeping incompatible batches in separate feed hoppers.|Real-time composition sensing and viscosity control for mixed local glass waste.|HEATED DIE|BATCH SELECTOR
road-mender|ROAD MENDER|CRACK-SEALING STREET CRAWLER|Maps a damaged road seam, cleans it and injects just enough repair material while traffic uses the next lane.|Durable bonding to variable wet and contaminated road surfaces without excessive preheating.|SEAM SHOE|METERING CARTRIDGE
fibre-braid|FIBRE BRAID|VARIABLE-ANGLE COMPOSITE LOOM|Braids hollow structural members around a moving form, changing fibre direction where loads will change.|Fast inspection of internal fibre placement before a defective part has been fully cured.|CARRIER TRACK|MANDREL CHUCK
metal-orchard|METAL ORCHARD|SORTED POWDER RECLAIMER|Turns a verified stream of metal offcuts into screened powder for local additive manufacturing.|Continuous chemistry verification and closed handling of reactive fine powders.|ATOMIZER THROAT|SIEVE CASSETTE
patch-arm|PATCH ARM|PORTABLE SURFACE REPAIR ROBOT|Clamps onto a damaged structure and rebuilds a small missing surface under a local shield instead of replacing the whole part.|Field deposition that bonds predictably to aged alloys without distorting the surrounding structure.|DEPOSITION WRIST|LOCAL SHIELD
ceramic-nest|CERAMIC NEST|MULTI-AXIS CERAMIC PRINTER|Builds interlocking refractory parts inside a heated cradle so unsupported walls stay where the design put them.|Consistent shrinkage compensation across mixed ceramic feedstocks and firing histories.|EXTRUSION HEAD|HEATED CRADLE
seam-surgeon|SEAM SURGEON|AUTONOMOUS PIPE-WELDING COLLAR|Travels around a pipe joint with synchronized preparation, welding and inspection tools. Its report includes the parts it refused to weld.|Closed-loop defect detection fast enough to adjust a weld before the flaw is buried.|ORBITAL TOOL CARRIAGE|INSPECTION SHOE
foam-forge|FOAM FORGE|CONTROLLED POROSITY CASTING CELL|Casts lightweight metal foam into serviceable molds while controlling where the strong ribs and open pores form.|Repeatable pore architecture and reliable inspection of hidden internal bridges.|GAS INJECTOR|SPLIT MOLD
thread-doctor|THREAD DOCTOR|GARMENT FIBRE REPAIR STATION|Finds a torn weave, identifies its yarn and replaces the damaged crossings under a small optical head.|Dexterous handling of loose fibres across many cloth structures and dyes.|MICRO LOOM|OPTICAL SHUTTLE
brick-return|BRICK RETURN|MASONRY RECLAMATION PRESS|Separates reusable bricks from demolition mortar with controlled vibration and broad compliant supports.|Reliable crack prediction that preserves old bricks with uncertain internal damage.|COMPLIANT JAW|MORTAR SEPARATOR''',
'mobility':'''manta-foil|MANTA FOIL|ELECTRIC HYDROFOIL FERRY|Lifts a small passenger cabin above harbour chop on retractable foils and returns to a shallow draft at the dock.|Fault-tolerant foil control and batteries suited to repeated fast marine charging.|FOIL ROOT|DUCTED PROPULSOR
snow-thread|SNOW THREAD|LOW-PRESSURE SNOW TRANSPORT|Carries supplies across soft snow on wide articulated tracks, spreading its load before a weak patch becomes a rescue call.|Reliable subsurface snow sensing and low-temperature energy storage.|TRACK BOGIE|SNOW PROBE
canyon-car|CANYON CAR|SUSPENDED VALLEY SHUTTLE|Moves a compact cabin along paired cables between settlements where a road would cut through the entire hillside.|Self-inspecting cables and recoverable propulsion after a mid-span drive failure.|TRACTION BOGIE|CABIN HANGER
rescue-fan|RESCUE FAN|DUCTED-LIFT MEDICAL CARRIER|Lowers a protected stretcher pod into a narrow landing site while its lift ducts remain above obstacles.|Quiet, fault-tolerant distributed lift with enough reserve for difficult rescue approaches.|LIFT DUCT|STRETCHER CRADLE
cargo-snake|CARGO SNAKE|ARTICULATED LAST-MILE TRAIN|Divides a large delivery into small powered segments that follow one another through narrow service streets.|Stable cooperative steering with safe separation when a pedestrian crosses the train.|ARTICULATED HITCH|DRIVE CORNER
dune-skimmer|DUNE SKIMMER|VARIABLE-FOOTPRINT DESERT ROVER|Changes wheel contact width as sand gets softer and parks behind its own folding shade when the day becomes too hot.|Sand-resistant shape-changing wheels with low rolling losses on firm ground.|EXPANDING WHEEL|SHADE HINGE
canal-thread|CANAL THREAD|AUTONOMOUS FREIGHT BARGE|Links low narrow cargo pods into a canal train and separates them at small urban docks.|Reliable close-quarters autonomy around locks, swimmers and uncooperative floating debris.|LOCKING COUPLER|AZIMUTH DRIVE
cliff-step|CLIFF STEP|ANCHORED CARGO CLIMBER|Moves crates up prepared cliff anchors on alternating load-bearing legs rather than hauling a whole cableway.|Verifiable contact and recovery after one anchor or actuator loses its grip.|ANCHOR CLAMP|LOAD TRANSFER LINK
island-wing|ISLAND WING|GROUND-EFFECT SUPPLY CRAFT|Uses a broad low wing to move bulky supplies between islands while staying close to the water.|Control that safely handles changing waves without relying on a perfectly flat sea.|WING BOX|SPRAY DEFLECTOR
rail-pod|RAIL POD|ON-DEMAND FREIGHT CAPSULE|Carries one small consignment through an existing rail corridor and waits in a siding instead of making the passenger train wait.|Rail operations that safely coordinate many small independent freight vehicles.|WHEEL MODULE|COUPLING NOSE''',
'instruments':'''hush-field|HUSH FIELD|LOCAL ACOUSTIC QUIET ARRAY|Reduces repetitive machinery noise inside a mapped work zone using microphones and independently aimed acoustic sources.|Stable control of moving broadband noise without making the next workbench louder.|SOURCE TILE|MICROPHONE TREE
memory-kiln|MEMORY KILN|LONG-LIFE GLASS DATA WRITER|Writes a family's archive into small glass plates and stores a readable decoding guide beside them. The password is not the only surviving artifact.|Fast error-checked volumetric writing and readers that remain reproducible centuries later.|FOCUS OBJECTIVE|PLATE CAROUSEL
quasar-clock|QUASAR CLOCK|TRANSPORTABLE OPTICAL TIMEBASE|Brings a stable optical reference to a field laboratory in a vibration-isolated transport case.|Optical clocks that recover automatically after travel without a room of specialists.|TRAP CHAMBER|LASER BENCH
stone-listener|STONE LISTENER|SUBSURFACE ACOUSTIC SCANNER|Places several contact shoes on old masonry and maps hidden voids before anyone decides where to drill.|Reliable inversion of wave signals through irregular, layered historical materials.|CONTACT SHOE|PHASED RECEIVER
dark-bloom|DARK BLOOM|LOW-LIGHT MULTISPECTRAL CAMERA|Opens a flower of small apertures to compare dim reflected light across many wavelengths without disturbing nocturnal wildlife.|Very low-noise detectors and stable registration between small independent optical channels.|FILTER WHEEL|DETECTOR COLD FINGER
gravity-pencil|GRAVITY PENCIL|PORTABLE MATTER-WAVE SENSOR|Measures small changes in local gravity from a stabilized field tripod, helping distinguish an underground cavity from a surface shadow.|Compact atom interferometry that keeps its sensitivity outside a quiet laboratory.|ATOM SOURCE|ISOLATION LEG
spectrum-harp|SPECTRUM HARP|FIELD CHEMICAL SPECTROMETER|Separates and measures a small unknown sample with a folded optical path that fits into a rugged carry frame.|Self-calibrating optics and contamination control under changing field conditions.|GRATING CARRIAGE|SAMPLE CELL
fault-lantern|FAULT LANTERN|STRUCTURAL STRAIN IMAGER|Scans loaded components and turns tiny surface motions into a map of where a crack may be growing.|Robust interferometric measurement on moving, dirty industrial surfaces.|SHEAROGRAPHY HEAD|REFERENCE MIRROR
neutrino-bell|NEUTRINO BELL|UNDERGROUND DETECTOR MODULE|Packs a serviceable optical sensor cluster into a shielded underground detector, listening for rare flashes rather than ordinary noise.|Affordable photosensors and long-lived calibration systems for extremely low-background measurements.|PHOTON SENSOR|CALIBRATION FEED
echo-cartographer|ECHO CARTOGRAPHER|CAVE MAPPING SCOUT|Builds a geometric map of a dark passage with complementary light and acoustic sensing, then returns along a verified route.|Autonomous navigation when dust, water and featureless walls defeat any single sensor.|SENSOR GIMBAL|RETRACTABLE WHEEL''',
'habitats':'''storm-petal|STORM PETAL|FOLDING EMERGENCY SHELTER|Unfolds rigid weather petals from a transport spine and seals a small warm room before the next squall reaches the site.|Light reusable seals that work after muddy field handling and hundreds of deployments.|PETAL HINGE|FLOOR SEAL
lunar-porch|LUNAR PORCH|DUST-SEPARATING AIRLOCK|Keeps abrasive lunar dust in an exterior suit dock while the occupant enters the clean habitat through the back of the suit.|Reliable rear-entry pressure seals and dust removal without consumable wash water.|SUIT DOCK|DUST TRAP
heat-window|HEAT WINDOW|SELECTIVE THERMAL FACADE|Changes a building panel's heat exchange while preserving useful daylight, reducing the fight between blinds and air conditioning.|Durable large-area optical layers that switch predictably after years outdoors.|OPTICAL LAMINATE|EDGE ACTUATOR
quiet-stair|QUIET STAIR|ADAPTIVE ACCESS RAMP|Converts a short public stair into a broad level platform and back again without asking its users to find a separate entrance.|Robust interlocks and load sensing in a mechanism exposed to rain, dirt and public use.|STEP LINKAGE|EDGE SENSOR
air-root|AIR ROOT|MODULAR INDOOR AIR SCRUBBER|Draws room air through separately replaceable particle, sorbent and biological stages with a visible path for service access.|Regeneration that removes captured pollutants without quietly returning them to the room.|SORBENT WHEEL|FLOW PLENUM
frost-house|FROST HOUSE|PASSIVE COLD-CHAIN CABINET|Keeps medicine in a monitored thermal envelope during unreliable power, using replaceable phase-change packs.|Compact thermal storage matched to precise medical temperature bands over long transport periods.|THERMAL CASSETTE|DOOR GASKET
bridge-kit|BRIDGE KIT|SELF-DEPLOYING FOOTBRIDGE|Rolls interlocking deck segments over a small gap while paired trusses unfold beneath them.|Safe autonomous verification of unknown banks and dependable recovery after interrupted deployment.|TRUSS KNUCKLE|DECK LOCK
sand-archive|SAND ARCHIVE|BURIED CULTURAL VAULT|Stores local records in a dry buried chamber with a replaceable access throat and a plainly documented opening mechanism.|Passive moisture control and packaging that can survive long periods without maintenance.|ACCESS THROAT|ARCHIVE DRAWER
floating-court|FLOATING COURT|MODULAR FLOOD REFUGE|Connects buoyant public platforms around a raised service core so a flooded neighbourhood retains a dry meeting place.|Self-aligning connectors and stable moorings that tolerate uneven loading and moving debris.|PLATFORM JOINT|MOORING CLEAT
shade-orchard|SHADE ORCHARD|CLIMATE-ADAPTIVE STREET CANOPY|Turns overhead louvers to shade pedestrians while preserving winter sunlight and emergency access.|Reliable distributed actuation with safe passive positions after power or communication failures.|LOUVER PIVOT|RAIN CHANNEL''',
'wearables':'''load-fern|LOAD FERN|PASSIVE CARGO SUPPORT FRAME|Transfers part of a carried load from a worker's shoulders toward the ground through a compliant external frame.|Comfortable load transfer that follows varied bodies without imposing an unnatural gait.|HIP COUPLING|SPRING PACK
hand-stead|HAND STEAD|TREMOR-COMPENSATING TOOL BRACE|Stabilizes a small tool relative to its handle so a person can keep doing precise work with an unsteady hand.|Compact control that distinguishes intention from tremor without fighting the user.|TOOL GIMBAL|COMPLIANT CUFF
breath-shell|BREATH SHELL|REGENERATIVE RESPIRATOR PACK|Routes exhaled air through a monitored regeneration cartridge for work in hostile atmospheres.|Safe compact regeneration and fault detection across changing humidity and contaminant loads.|SCRUBBER CARTRIDGE|BREATHING VALVE
stride-return|STRIDE RETURN|ADAPTIVE ANKLE ASSIST|Stores a portion of walking energy in a tuned spring and returns it near push-off while adapting to stairs.|Reliable phase detection and comfortable assistance without forcing the ankle into a fixed path.|ANKLE CAM|ELASTIC CARTRIDGE
cold-mantle|COLD MANTLE|PERSONAL THERMAL HARNESS|Circulates a small thermal buffer around a worker instead of cooling an entire open-air job site.|Light quiet thermal storage and safe skin contact during long humid shifts.|MICROCHANNEL PANEL|THERMAL BUFFER
reach-friend|REACH FRIEND|SHOULDER-ASSIST TOOL YOKE|Supports the weight of a tool during overhead repair while leaving the user's hands responsible for the work.|Low-friction assistance that stays aligned with the shoulder through awkward reaches.|SHOULDER LINK|BALANCE SPRING
balance-thread|BALANCE THREAD|HAPTIC NAVIGATION BELT|Turns nearby obstacles and route cues into small directional pressures around the waist, leaving the ears free.|Comfortable low-latency cues that remain interpretable during complex everyday movement.|TACTILE TILE|DEPTH SENSOR
dive-spine|DIVE SPINE|MODULAR SHALLOW-WATER DIVE RIG|Carries breathing, buoyancy and inspection modules close to a diver's body with clear access to emergency releases.|Reliable modular life-support interfaces that cannot be connected in an unsafe configuration.|BUOYANCY VALVE|QUICK RELEASE
grip-print|GRIP PRINT|CUSTOM FIT PROSTHETIC HAND|Uses an individually fitted palm and serviceable tendon drive to grasp ordinary tools without a menu of theatrical gestures.|Durable tactile feedback and intuitive control that remain useful outside a clinical demonstration.|TENDON DIFFERENTIAL|PALM SENSOR
sleep-cocoon|SLEEP COCOON|MOBILE REST SUPPORT SEAT|Supports the head, pelvis and feet during long field shifts so a short planned rest does not become a new neck injury.|A compact adjustable support system that verifies posture while preserving quick emergency exit.|HEAD CRADLE|SEAT LINKAGE''',
'domestic':'''sock-oracle|SOCK ORACLE|LAUNDRY PAIR RECOVERY|Sorts clean socks by weave, wear and owner before announcing that the missing partner is not in the machine. It has learned to sound apologetic.|Cloth perception and gentle manipulation reliable enough for tangled mixed household laundry.|SOFT SORTING DRUM|PAIRING GATE
snooze-engine|SNOOZE ENGINE|ESCALATING WAKE-UP DEVICE|Starts with a quiet light and gradually moves the alarm farther from the bed. The final stage requires walking, which marketing calls wellness.|Reliable room mapping and consent-aware scheduling that survives an owner's half-asleep countermeasures.|TRAVELLING CHIME|DRIVE FOOT
advice-filter|ADVICE FILTER|UNREQUESTED OPINION INTERCEPTOR|Recognizes the phrase 'what you should do' and delays the room speaker until the listener explicitly asks for the rest.|Context recognition that can distinguish welcome advice from a long interruption.|ACOUSTIC SHUTTER|CONSENT BUTTON
later-anchor|LATER ANCHOR|PROCRASTINATION DESK TIMER|Physically parks distracting devices in a timed drawer. The override key is included, labelled, and deliberately placed in another room.|A locking mechanism honest enough to remain useful after its owner discovers every shortcut.|TIMED LATCH|DEVICE CRADLE
pet-diplomat|PET DIPLOMAT|HOUSEHOLD ANIMAL REQUEST TERMINAL|Combines routine, posture and context to suggest what a pet may want. 'Open the door so I can reconsider' remains the most common output.|Animal-behaviour models that report uncertainty instead of confidently inventing a translation.|GESTURE CAMERA|REQUEST PADDLE
meeting-buoy|MEETING BUOY|CONVERSATION TIME KEEPER|Raises a small visible flag when a meeting spends longer discussing its format than its subject. The flag is not connected to a mute button.|Robust topic tracking that separates necessary context from a carefully disguised postponement.|FLAG ACTUATOR|ROOM MICROPHONE
queue-garden|QUEUE GARDEN|PATIENT WAITING COMPANION|Grows one mechanical leaf for each completed queue position. It refuses to estimate five minutes unless five minutes has ever happened here.|Trustworthy queue sensing across interruptions, priority cases and missing tickets.|LEAF REGISTER|TICKET READER
compliment-mill|COMPLIMENT MILL|CONTEXTUAL PRAISE DISPENSER|Produces one specific, defensible compliment after inspecting a completed piece of work. It rejects the word 'amazing' when nothing was examined.|Models that ground praise in observable details without confusing politeness with evidence.|OBSERVATION HEAD|PRINT MECHANISM
crumb-pilot|CRUMB PILOT|TABLETOP CLEANING SCOUT|Maps crumbs between dishes and sweeps them into a removable hopper. It stops at the edge even when the biscuit is clearly worth the risk.|Reliable small-scale perception around reflective cutlery, liquids and moving hands.|EDGE WHISKER|VACUUM THROAT
plant-alibi|PLANT ALIBI|HOUSEPLANT CARE RECORDER|Records actual watering and light exposure before an owner blames the plant for being difficult. The history cannot be edited from the watering can.|Cheap root-zone sensing that separates drought from overwatering in mixed household pots.|ROOT PROBE|WATER METER'''
}
PALETTES=['navy','teal','rust','plum','grass','indigo','umber','royal','olive','wine','petrol','violet','sand','graphite']
SOURCE_GROUPS={
'orbit':('Solar sailing, electric propulsion and deployable spacecraft structures.',['https://www.nasa.gov/space-technology-mission-directorate/tdm/solar-electric-propulsion/','https://www.nasa.gov/space-technology-mission-directorate/tdm/solar-sail-demonstrator-sunjammer/']),
'energy':('Marine energy, mechanical storage and established heat-transfer principles.',['https://www.energy.gov/eere/water/marine-energy-basics']),
'water':('Membrane separation, condensation and environmental sensing.',['https://www.epa.gov/waterreuse/basic-information-about-water-reuse']),
'biology':('Controlled cultivation, restoration robotics and environmental monitoring.',['https://oceanacidification.noaa.gov/ocean-acidification-research/ocean-acidification-monitoring/']),
'fabrication':('Additive manufacturing, materials metrology and selective repair.',['https://www.nist.gov/additive-manufacturing/research-areas/materials/metals']),
'mobility':('Electric propulsion, articulated vehicles and conventional load paths.',['https://www.energy.gov/eere/vehicles/vehicle-technologies-office']),
'instruments':('Optical metrology, sensor fusion and physical measurement.',['https://www.nist.gov/pml']),
'habitats':('Deployable structures, passive thermal control and modular services.',['https://www.nasa.gov/reference/environmental-control-and-life-support-systems-eclss/']),
'wearables':('Assistive mechanisms, compliant interfaces and human-centred robotics.',['https://www.nibib.nih.gov/science-education/science-topics/rehabilitation-engineering']),
'domestic':('Robotic sensing and manipulation; humorous capabilities remain fictional.',['https://www.nist.gov/el/intelligent-systems-division-73500'])}


def main():
    if (ROOT/'docs/century/catalog.json').exists():
        raise SystemExit('Reviewed catalog exists. Edit catalog via registry.update; seeding is only for an empty collection.')
    path=ROOT/'docs/century/catalog.json';old={e['slug']:e for e in json.loads(path.read_text())} if path.exists() else {}
    groups={k:[row.split('|') for row in v.splitlines()] for k,v in DOMAINS.items()};entries=[]
    assert all(len(v)==10 for v in groups.values())
    for batch in range(10):
        for group,rows in groups.items():
            slug,title,role,story,breakthrough,b,c=rows[batch];number=len(entries)+1
            entry={'number':number,'slug':slug,'title':title,'domain':group,'recipe':slug.replace('-','_'),'category':'satire' if group=='domestic' else 'serious','purpose':role,'narrative':story,'required_breakthroughs':breakthrough,'real_basis':SOURCE_GROUPS[group][0],'sources':SOURCE_GROUPS[group][1],'view_A':role,'view_B':b,'view_C':c,'human_role':'wearer' if group=='wearables' else 'none','palette':PALETTES[(number*5+batch)%len(PALETTES)],'service_year':str(2043+(number*7)%39),'model':f'{"".join(w[0] for w in title.split())[:3]}-{batch+1}','seed':31000+number*131,'parameters':[['STATUS','DESIGN STUDY'],['SERIES',f'{number:03d} / 100'],['GEOMETRY','ILLUSTRATIVE'],['DATA','NO MEASURED CLAIMS']],'source_files':[f'tools/century/{group}.py','tools/century/render.py'],'status':'idea','review_notes':[]}
            for key in ('status','review_notes','validation','rendered','built'):
                if key in old.get(slug,{}):entry[key]=old[slug][key]
            entries.append(entry)
    assert len(entries)==100 and len({x['slug'] for x in entries})==100
    path.write_text(json.dumps(entries,indent=2,ensure_ascii=False)+'\n')
    md=['# Century — 100 nowych koncepcji','', 'Numery odnoszą się do nowej kolekcji. Wszystkie urządzenia są koncepcjami; zakres spekulacji opisano indywidualnie.','']
    for e in entries:md += [f"## {e['number']:03d} — {e['title']}",e['narrative'],'',f"**A:** {e['view_A']} · **B:** {e['view_B']} · **C:** {e['view_C']}",'',f"Wymagany przełom: {e['required_breakthroughs']}",'']
    (ROOT/'docs/century/CONCEPTS.md').write_text('\n'.join(md))
    print('100 unique concepts registered')
if __name__=='__main__':main()
