"""Add eight individually authored concepts; never alter the rejected century."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
SPECS=[
(101,'velvet-hammer','orbital','NON-PYROTECHNIC PAYLOAD RELEASE','Releases an orbital payload by transferring preload before retracting the retaining jaws. The separation should make an event log, not an entrance.','Non-pyrotechnic release mechanisms and controlled transfer of stored strain energy.','A flight-qualified synchronised release that stays reliable through thermal cycling and contamination.','OPEN LOAD-TRANSFER COLLAR','TRANSFER CAM CASSETTE','EVENT STRIP RECORDER','ROLLER / RETURN SPRING / RETAINING JAW','TIME TAGS / RELEASE IS NOT ZERO SHOCK','umber','VH-3','2072','https://ntrs.nasa.gov/api/citations/19970021613/downloads/19970021613.pdf'),
(103,'bubble-bailiff','habitats','MICROGRAVITY COOLANT GAS TRAP','Separates stray gas from a recirculating coolant loop when bubbles refuse to rise. The gas is held in custody until a controlled vent is available.','Wetted capillary membranes can exclude gas below their bubble-point pressure.','Coolant-compatible surface chemistry and a recoverable separator that resists fouling.','SINUOUS SEPARATION MANIFOLD','WETTED MEMBRANE DRAWER','GAS CUSTODY BUFFER','WICK SUPPORT / FLOW CHANNELS / RETAINERS','ISOLATION STEM / VENT WHEEL / INVENTORY','navy','BB-2','2076','https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20100033580.pdf'),
(104,'key-concord','civic','TWO-PERSON CONSENT LATCH','Opens a shared compartment only while two independent key holders agree. Rank, urgency and a louder voice do not count as a second key.','Mechanical interlocks can implement two independent permissive conditions.','A tamper-evident, fail-secure mechanism with a separately defined emergency procedure.','EQUAL-AUTHORITY LOCKBODY','COINCIDENCE YOKE','RETRACTABLE KEEPER','TWO BARRELS / ONE SHARED PERMISSION','BOLT / RETURN SPRING / WITNESS WINDOW','grass','KC-2','2068',''),
(105,'metric-embassy','industry','CONNECTOR COMPATIBILITY STATION','Identifies a visiting connector before authorising an adapter. A thread that goes in is considered an introduction, not proof of compatibility.','Dimensional metrology and thread pitch-diameter measurement using calibrated gauges.','A verified interface library covering mechanical, electrical and fluid compatibility.','OPEN GAUGE CAROUSEL','THREE-WIRE PROBE HEAD','KEYED ADAPTOR CARTRIDGE','CONTACT WIRES / TRAVEL / ZERO REFERENCE','THREAD CRESTS / CONTACT PINS / POLARISATION','graphite','ME-7','2071','https://www.nist.gov/publications/pitch-diameter-measurement-threaded-gages-using-cmm'),
(106,'muon-customs','science','PASSIVE CARGO SCATTERING TOMOGRAPH','Studies a sealed cargo bay using naturally arriving cosmic-ray muons. Suspicious density is reconstructed slowly; the sky does not accept priority boarding.','Muon scattering tomography estimates material distribution from measured incoming and outgoing tracks.','Robust reconstruction with sparse tracks and carefully characterised detector backgrounds.','OPEN COSMIC INSPECTION GANTRY','TRACKING PLANE CASSETTE','COINCIDENCE CLOCK RACK','STAGGERED LAYERS / EVENT COORDINATES','TIMESTAMP / MATCH / RETAIN THE RAW TRACK','wine','MC-4','2081','https://laro.lanl.gov/esploro/outputs/journalArticle/Tomographic-Imaging-with-Cosmic-Ray-Muons/9916364485503761'),
(107,'resonance-tailor','industry','CLAMP-ON TUNED MASS ABSORBER','Fits an awkward machine with three adjustable resonant branches. Each branch takes a narrow band of vibration personally.','Tuned mass absorbers exchange vibration energy with a host near their selected resonances.','Durable tuning locks and verified performance across changing host loads and temperatures.','THREE-BAND ABSORBER CROWN','MOVING MASS BRANCH','CROSSED-FLEXURE LOCK','PARALLEL LEAVES / TRAVEL / TUNING SCREW','LOCK SCREWS / COMPLIANT GUIDE / STOP','violet','RT-3','2069','https://technology.nasa.gov/patent/LAR-TOPS-189'),
(108,'suture-loom','medicine','EXPERIMENTAL NEEDLE HANDOFF MODULE','Passes a curved needle between opposing grippers while a dancer manages thread slack. This bench study uses a test membrane; the patient is the research schedule.','Robotic needle manipulation and tension control have been studied for automated suturing.','Validated tissue interaction, sterilisation and fault recovery before any clinical application.','OPEN NEEDLE-HANDOFF TRACK','OPPOSED NEEDLE GRIPPERS','THREAD DANCER CARTRIDGE','ALTERNATING HOLD / CURVED TEST NEEDLE','SPOOL / TENSION ARM / SLACK RECOVERY','grass','SL-2','2084','https://arxiv.org/abs/2002.00530'),
(110,'spin-table','habitats','BOWL-SCALE ROTATING GALLEY','Keeps dinner inside a sealed rotating vessel with a balanced cradle and an interlocked lid. Artificial gravity is available in the serving size only.','Centripetal acceleration is proportional to radius and angular speed squared.','A safe balanced rotor with food-compatible seals and dependable stopped-rotor transfer.','BALANCED ROTATING VESSEL','DRIVE AND REACTION BEARING','INTERLOCKED TRANSFER LID','REDUCTION / TORQUE RETURN / SERVICE GAUGE','THREE LATCHES / SEAL / EQUALISATION PORT','umber','ST-1','2078','https://science.nasa.gov/learn/basics-of-space-flight/chapter3-3/')]

def entries():
 for n,slug,domain,purpose,narrative,basis,needed,a,b,c,bn,cn,palette,model,year,url in SPECS:
  yield dict(number=n,slug=slug,title=slug.replace('-',' ').upper(),domain=domain,recipe=slug.replace('-','_'),category=purpose,purpose=purpose,narrative=narrative,real_basis=basis,required_breakthroughs=needed,view_A=a,view_B=b,view_C=c,view_B_note=bn,view_C_note=cn,palette=palette,model=model,service_year=year,human_role='none',seed=190001+n*137,series_total=110,parameters=[['STATUS','ORIGINAL CONCEPT STUDY']],sources=[url] if url else [],source_scope='Established principle; original speculative hardware. Diagram models and fictional records explicitly scoped.',source_files=['tools/century/extension_geometry.py','tools/century/extension_editorial.py'],status='planned',review_notes=[],curation={'status':'retained','review':'autonomous extension to 42','reason':'Distinct mechanism, service geometry and editorial diagrams; no recycled rejected concept.'})

if __name__=='__main__':
 p=ROOT/'docs/century/catalog.json';cat=json.loads(p.read_text());present={e['number'] for e in cat}
 cat.extend(e for e in entries() if e['number'] not in present)
 p.write_text(json.dumps(cat,indent=2,ensure_ascii=False)+'\n')
